//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace upb.tabd.broker
{
    using System;
    using System.Collections.Generic;

    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.ControlPesoes = new HashSet<ControlPeso>();
            this.DetalleVacunas = new HashSet<DetalleVacuna>();
        }

        public int IdentMascota { get; set; }
        public string NombreMascota { get; set; }
        public int IdentRaza { get; set; }
        public int IdentEspecie { get; set; }
        public double IdentCliente { get; set; }

        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlPeso> ControlPesoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVacuna> DetalleVacunas { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual Raza Raza { get; set; }
    }
}
